# Beam Search Algorithm
by: Arvin

A beam search algorithm to solve RNN output (probabilities data). The function receives only csv file with semicolon (;) as the delimiter.

### Spec
|Libraries        |Version    |
|-----------------|-----------|
|Numpy            |1.20.1     |

In [1]:
import numpy as np

In [2]:
# FUNCTIONS

# Soft max algorithm
def softmax(mtx:np.ndarray):
    newMtx = np.empty((0, np.shape(mtx)[1]), float)
    for i in range(len(mtx)):
        newMtx = np.vstack((newMtx, np.divide(np.exp(mtx[i]), np.sum(np.exp(mtx[i])))))
    return newMtx

In [3]:
# CONFIGS

beamWidth = 3 # Beam width

filePath = "../assets/data/line/rnnOutput.csv"

# Classes
c = np.append(np.array(list(" !\"#&'()*+,-./0123456789:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz")), "")

In [4]:
# Import CSV data
csv = np.genfromtxt(filePath, delimiter=";")

In [5]:
# CALCULATIONS (MAIN FUNCTION)

mtx = softmax(csv) # Value matrix (possibilities) after using softmax algorithm
indexes = np.empty((0,beamWidth), int) # Top [beamWidth] biggest possibilities's indexes of each rows in matrix

# Get top [beamWidth] values' indexes
# OLD METHOD:
#   for i in range(len(mtx)):
#       maxVals = np.sort(mtx[i])[:-beamWidth-1:-1] # Get the top [beamWidth] values
#       rawIndexes = np.concatenate([(np.where(mtx[i] == v)[0]) for v in maxVals]) # Get the indexes (positions) of the values in each rows
#       _, index = np.unique(rawIndexes, return_index=True) # Get only the unique indexes
#       indexes = np.vstack((indexes, rawIndexes[np.sort(index)]))
for i in range(len(mtx)):
    rawIndexes = np.argsort(mtx[i])[:-beamWidth-1:-1]
    indexes = np.vstack((indexes, rawIndexes))

paths = indexes[0].reshape(beamWidth,1) # Result paths holder
# Get the indexes of top [beamWidth] biggest probability
for i in range(1, len(indexes)):
    # np.argsort always increase sort. Therefore, it needs to be reversed by using [:-beamWidth-1:-1]
    topIndexes = np.argsort(np.concatenate([mtx[i][indexes[i]] * x for x in mtx[i-1][paths.T[-1]]]), kind="mergesort")[:-beamWidth-1:-1]
    nxt = topIndexes % beamWidth # Next indexes position
    prev = (topIndexes - nxt)//beamWidth # Previous indexes position
    paths = np.concatenate((paths[prev], indexes[i][nxt].reshape(beamWidth,1)), axis=1)

# Print out the result
for res in c[paths]:
    print(''.join(res))

the  fak  ffriendd  oof  thhe   fomlyy  haee  tC
Hhe  fak  ffriendd  oof  thhe   fomlyy  haee  tC
he  fak  ffriendd  oof  thhe   fomlyy  haee  tC


In [6]:
# DUMMY TEST

beamWidth = 3
values = np.array([
    [0.1,0.3,0.3],
    [0.5,0.6,0.4],
    [0.1,0.3,0.2],
    [0.9,0.8,0.7],
])

indexes = np.array([
    [2,1,0],
    [1,0,2],
    [1,2,0],
    [0,1,2],
])

paths = indexes[0].reshape(beamWidth,1) # Result paths holder
# Get the indexes of top [beamWidth] biggest probability
for i in range(1, len(indexes)):
    # np.argsort always increase sort. Therefore, it needs to be reversed by usin [:-beamWidth-1:-1]
    topIndexes = np.argsort(np.concatenate([values[i][indexes[i]] * x for x in values[i-1][paths.T[-1]]]), kind="mergesort")[:-beamWidth-1:-1]
    nxt = topIndexes % beamWidth # Next indexes position
    prev = (topIndexes - nxt)//beamWidth # Previous indexes position
    paths = np.concatenate((paths[prev], indexes[i][nxt].reshape(beamWidth,1)), axis=1)
print(paths)

[[1 0 1 0]
 [1 1 1 0]
 [2 1 1 0]]
