In [1]:
import numpy as np

In [22]:
def calc_neurons(inputs:np.ndarray, weights:np.ndarray, biases:np.ndarray):
    return (np.dot(inputs, weights.T) + biases)

In [23]:
inputs = np.array([
    [1,2,3, 2.5],
    [2.0,5.0,-1.0,2.0],
    [-1.5,2.7,3.3,-0.8],
])

weights = np.array([
    [0.2,0.8,-0.5,1.0],
    [0.5,-0.91,0.26,-0.5],
    [-0.26,-0.27,0.17,0.87],
])

biases = np.array([2,3,0.5])

out1:np.ndarray = calc_neurons(inputs, weights, biases)
out1

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

In [24]:
weights2 = np.array([
    [0.1, -0.14, 0.5],
    [-0.5, 0.12, -0.33],
    [-0.44, 0.73, -0.13],    
])

biases2 = np.array([-1, 2, -0.5])

out2:np.ndarray = calc_neurons(out1, weights2, biases2) 
out2

array([[ 0.5031 , -1.04185, -2.03875],
       [ 0.2434 , -2.7332 , -5.7633 ],
       [-0.99314,  1.41254, -0.35655]])

In [57]:
class LayerDense:
    weights:np.ndarray = np.empty(0)
    biases:np.ndarray = np.empty(0)
    output:np.ndarray = np.empty(0)
    
    def __init__(self, nInputs:int, nNeurons:int):
        self.weights = 0.1 * np.random.randn(nInputs, nNeurons)
        self.biases = np.zeros((1, nNeurons))
    
    def next(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [58]:
np.random.seed(0)
l = LayerDense(4, 5)
l2 = LayerDense(5, 2)

l.next(inputs)
l2.next(l.output)
l2.output

array([[ 0.148296  , -0.08397602],
       [ 0.14100315, -0.01340469],
       [ 0.20124979, -0.07290616]])